### PR TITLE
Dev: event callback facilities to stateful handlers

### PR DESCRIPTION
**Pull request by builtinnya**
Got inspired by Mikko, I've added thin wrapper for (un)registering event callbacks
to stateful handlers and rewritten !call as a stateful handler (not a built-in command.)

Better way that routes skype events to the handlers may exist, but this seems to be the simplest one.

### CODE REVIEW

**Comment by miohtama** [comment]
Ok there you go. I changed API name a bit, so if you can please confirm if the changes still work for you.

Also: Need Sphinx docs updates regarding !call :)

**Comment by miohtama** [comment]
I need to change this that we pass Sevabot instance instead of Skype... You need to access Sevabot level variables and functions (getChatById) in modules.

**Comment by miohtama** [comment]
I just tested !call at the dev branch and looks like everything is working perfectly.

Also: now Tasks example contains Timer which shows how to do timed messages

**Comment by miohtama** [comment]
Updated also related docs. Can you please test one more time yourself and this is good to release :)

**Comment by builtinnya** [comment]
Nice work!
I tested !call and !tasks briefly and looks like everything is ok, too.

It is good time to release version 1.2 :)

**Comment by builtinnya** [comment]
Oops. One more thing.

I think it is better to add `custom/*` or something like that to `.gitignore` so users can fit his/her own repo
for custom handlers.

**Comment by miohtama** [comment]
Ok. I'll add it

**Comment by miohtama** [comment]
Here we go: https://github.com/opensourcehacker/sevabot/commit/ab77ed22ea04e94ec88c21163984d149a5f3c6b3

**Pull request merged**
