### PR TITLE
Основное обновление

### PR DESCRIPTION
**Pull request by wmzaru**

### CODE REVIEW

**Comment by miohtama** [comment]
I am not sure if I want to replace English texts with Russian texts. If you want localization please do it properly using Python gettext libraries or so.

If you are unsure how to do localization please open an issue and ask first.

**Comment by miohtama** [comment]
Also use proper git commit messages.

**Comment by grundic** [comment]
Yep, not a very good descision.
Lokk here for [internationalization](Internationalization)

**Comment by wmzaru** [comment]
I'm sorry. Just accidentally clicked the Pull Requests .

**Comment by miohtama** [comment]
I was thinking so. No problem )

**Comment by miohtama** [comment]
You know you will lose your changes if Sevabot master changes? If you need Russian translations we can do proper internationalization with gettext.

**Pull request closed without merging**
