### PR TITLE
Added a /jenkins-notifier that works with existing jenkins-notification ...

### PR DESCRIPTION
**Pull request by bjjsre**
...plugin

https://wiki.jenkins-ci.org/display/JENKINS/Notification+Plugin

### CODE REVIEW

**Comment by miohtama** [comment]
Also another Q: I have started a new Sphinx based documentation. Would you mind to drop jenkins.rst (copy e.g. zabbix.rst) and explain how to use Jenkins integration?

**Comment by tenpn** [comment]
Wow this is amazing. I've actually spent the better part of three hours trying various plugins to make Jenkins talk to the local sevabot server. Would love this to get into the main repro.

**Comment by tenpn** [comment]
...I know this isn't jenkins tech support, but would there be a way with this end-point link-up of only notifying on failed builds, rather than all builds?

**Comment by miohtama** [comment]
@tenpn  Try open a new issue if you need help. We do not currently have other media to discuss besides the issue tracker.

**Comment by miohtama** [comment]
Done!

**Pull request merged**
