### PR TITLE
Fix settings.py not found

### PR DESCRIPTION
**Pull request by bkmeneguello**

### CODE REVIEW

**Comment by miohtama** [comment]
Thanks!

**Comment by comentarinformal** [comment]
Now these lines appear all the time when using start-server:
/home/skype/sevabot/scripts/start-server.sh: line 21: +DIR=/home/skype/sevabot/scripts: No such file or directory
/home/skype/sevabot/scripts/start-server.sh: line 23: +cd: command not found

plus, I still get 
Could not load settings file: settings.py

**Comment by miohtama** [comment]
Ok let me check this today.

**Comment by comentarinformal** [comment]
Not wanting to put you on a hurry, of course, but... Is there any updates in your findings?
I'm starting to miss having a bot to say silly phrases every often.

**Comment by miohtama** [comment]
ooops, forgot this.

The first error looks like some kind of installation error amd should be fixed with a reinstall.

The second error is a missing file, because there is no default settings.py as it contains a password. Instead, you need to create the this from a supplied default file.

https://sevabot-skype-bot.readthedocs.org/en/latest/ubuntu.html#installing-sevabot

Please reopen the issue if you need further instructions. And feel free to pop up in IRC. Thanks!

**Comment by miohtama** [comment]
Also if the first error persists it might be also some OS specific error. Try running from command line:

```
     DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
     echo $DIR
```

**Pull request merged**
